# Generated by Django 5.1.7 on 2025-04-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0006_remove_arraivuser_google_refresh_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDevice",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="health_device",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("device_brand", models.CharField(max_length=50)),
                ("device_name", models.CharField(max_length=100)),
                ("token_string", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("steps", models.PositiveIntegerField(blank=True, null=True)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("hrv", models.FloatField(blank=True, null=True)),
                ("stress", models.FloatField(blank=True, null=True)),
                ("sleep_score", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="healthdevice.healthdevice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device"], name="healthdevic_device__d4838d_idx"
                    ),
                    models.Index(fields=["date"], name="healthdevic_date_431948_idx"),
                    models.Index(
                        fields=["device", "date"], name="healthdevic_device__743d98_idx"
                    ),
                ],
                "unique_together": {("device", "date")},
            },
        ),
    ]
