# Generated by Django 5.1.7 on 2025-04-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_arraivuser_health_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDevice',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_device', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('device_name', models.CharField(max_length=100)),
                ('device_brand', models.CharField(max_length=50)),
                ('registered_date', models.DateTimeField()),
                ('display_name', models.CharField(max_length=150)),
                ('token_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('body_battery', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_score', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_hrv', models.FloatField(blank=True, null=True)),
                ('sleep_deep', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_rem', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_light', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_stress', models.FloatField(blank=True, null=True)),
                ('resting_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_avg_hrv', models.PositiveIntegerField(blank=True, null=True)),
                ('hrv_baseline_low', models.PositiveIntegerField(blank=True, null=True)),
                ('hrv_baseline_high', models.PositiveIntegerField(blank=True, null=True)),
                ('hrv_status', models.CharField(blank=True, max_length=30, null=True)),
                ('moderate_intensity_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('vigorous_intensity_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('stress', models.PositiveIntegerField(blank=True, null=True)),
                ('resting_stress', models.PositiveIntegerField(blank=True, null=True)),
                ('low_stress', models.PositiveIntegerField(blank=True, null=True)),
                ('medium_stress', models.PositiveIntegerField(blank=True, null=True)),
                ('high_stress', models.PositiveIntegerField(blank=True, null=True)),
                ('stress_status', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='healthdevice.healthdevice')),
            ],
            options={
                'get_latest_by': 'date',
                'indexes': [models.Index(fields=['device'], name='healthdevic_device__d4838d_idx'), models.Index(fields=['date'], name='healthdevic_date_431948_idx'), models.Index(fields=['device', 'date'], name='healthdevic_device__743d98_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
