# Generated by Django 5.1.7 on 2025-04-17 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthdevice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymetrics",
            name="hrv",
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="body_battery",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="high_stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="hrv_baseline_high",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="hrv_baseline_low",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="hrv_status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="low_stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="medium_stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="moderate_intensity_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="resting_stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="sleep_hrv",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="stress_status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="vigorous_intensity_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="vo2max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="weekly_avg_hrv",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailymetrics",
            name="sleep_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailymetrics",
            name="stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
