# Generated by Django 5.1.7 on 2025-04-17 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthdevice",
            "0002_remove_dailymetrics_hrv_dailymetrics_body_battery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdevice",
            name="display_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
