# Generated by Django 5.1.7 on 2025-04-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthdevice", "0006_alter_dailymetrics_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymetrics",
            name="vo2max",
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="resting_heart_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="sleep_deep",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="sleep_light",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="sleep_rem",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="sleep_stress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
