# Generated by Django 5.1.7 on 2025-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arraivuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arraivuser',
            name='last_name',
        ),
    ]
