# Generated by Django 5.1.7 on 2025-04-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_arraivuser_google_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="arraivuser",
            name="health_device_added",
            field=models.BooleanField(default=False),
        ),
    ]
