# Generated by Django 5.1.7 on 2025-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_arraivuser_health_device_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arraivuser",
            name="health_device_added",
        ),
        migrations.AddField(
            model_name="arraivuser",
            name="health_device_status",
            field=models.CharField(default="virgin", max_length=20),
        ),
    ]
