# Generated by Django 5.1.7 on 2025-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_arraivuser_health_device_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arraivuser",
            name="health_device_status",
            field=models.CharField(default="absent", max_length=20),
        ),
    ]
