# Generated by Django 5.1.7 on 2025-04-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_arraivuser_health_device_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arraivuser",
            name="health_device_status",
        ),
    ]
