# Generated by Django 5.1.7 on 2025-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_arraivuser_health_device_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="arraivuser",
            name="health_device_status",
            field=models.CharField(default="absent", max_length=20),
        ),
    ]
